---
- name: ipython profile create pyspark
  command: "ipython profile create pyspark"
  tags: ipython-notebook-pyspark

- name: copy ipython_notebook_config.py
  template: src=ipython_notebook_config.py dest=~/.ipython/profile_pyspark/ipython_notebook_config.py
  tags: ipython-notebook-pyspark

- name: copy 00-pyspark-setup.py
  template: src=00-pyspark-setup.py dest=~/.ipython/profile_pyspark/startup/00-pyspark-setup.py
  tags: ipython-notebook-pyspark

- name: make directories for jupyterd
  file: path={{ item }} owner=dsl group=dsl state=directory
  with_items:
    - /var/log/jupyterd
  tags: ipython-notebook-pyspark

- name: copy start_notebook_pyspark.sh
  template: src=start_notebook_pyspark.sh dest=~/.ipython/start_notebook_pyspark.sh mode=0744
  sudo: yes
  sudo_user: dsl
  tags: ipython-notebook-pyspark

- name: create init.d script
  template: src=init.d.jupyterd dest=/etc/init.d/jupyterd mode=0755
  tags: ipython-notebook-pyspark

- name: chkconfig jupyterd on
  service: name=jupyterd enabled=yes
  tags: ipython-notebook-pyspark

