---
# file: roles/mysql-connector/tasks/main.yml

- name: get mysql-connector
  copy: src=/usr/local/src/mysql-connector-java-5.1.36.tar.gz dest=/usr/local/src/mysql-connector-java-5.1.36.tar.gz
  tags: mysql-connector

- name: decompression tar.gz file
  command: tar -zxvf /usr/local/src/mysql-connector-java-5.1.36.tar.gz -C /usr/local/src/
  tags: mysql-connector

- name: mkdir /usr/share/java
  command: mkdir -p /usr/share/java
  tags: mysql-connector

- name: copy mysql-connector
  command: cp /usr/local/src/mysql-connector-java-5.1.36/mysql-connector-java-5.1.36-bin.jar /usr/share/java/mysql-connector-java.jar
  tags: mysql-connector
