---
- name: install requirements
  yum: name={{ item }} state=installed
  with_items: 
    - gcc
    - python-devel
    - python-setuptools
  tags: pip

- name: install pip
  easy_install: name=pip
  tags: pip
