---
- name: create a new elb cross availability
  ec2_elb_lb:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    name: "{{ service name }}"
    scheme: internal
    state: present
    region: "{{ region }}"
    subnets: "{{ subnet }}"
    security_group_ids: "{{ sgroup }}"
    listeners:
      - protocol: tcp
        load_balancer_port: 8000
	instance_protocol: tcp
        instance_port: 8000
    health_check:
        ping_protocol: tcp
        ping_port: 8000
        ping_path: "/queries.json"
        response_timeout: 5
        interval: 60
        unhealthy_threshold: 2
        healthy_threshold: 10
