---
- name: Create the VPC 
  ec2_vpc:
    state: present
    region: "{{ region }}"
    ec2_access_key: "{{ aws_access_key_id }}"
    ec2_secret_key: "{{ aws_secret_access_key }}"
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    subnets: "{{ vpc_subnets }}"
    internet_gateway: "{{ vpc_internet_gateway|string }}"
    route_tables: "{{ vpc_route_tables }}"
    wait: true
  register: vpc
