---
# file: roles/base/tasks/main.yml

- name: mkdir /root/.ssh
  file: path=/root/.ssh state=directory
  ignore_errors: True
  tags: base

- name: configure nopass ssh for clusters authorized_keys
  template: src=authorized_keys dest=/root/.ssh/authorized_keys mode=0600
  ignore_errors: True
  tags: base

- name: configure nopass ssh for clusters id_rsa
  template: src=id_rsa dest=/root/.ssh/id_rsa mode=0600
  ignore_errors: True
  tags: base

- name: configure sshd_config don't use dns when ssh login
  template: src=sshd_config dest=/etc/ssh/sshd_config
  ignore_errors: True
  tags: base

- name: configure ssh_config don't ask when ssh login
  template: src=ssh_config dest=/etc/ssh/ssh_config
  ignore_errors: True
  tags: base

- name: configure i18n
  template: src=i18n dest=/etc/sysconfig/i18n
  ignore_errors: True
  tags: base

- name: configure network devicename from em to eth
  command: /bin/mv /etc/sysconfig/network-scripts/ifcfg-em1 /etc/sysconfig/network-scripts/ifcfg-eth0
  ignore_errors: True
  tags: base

- name: configure network devicename from em to eth
  command: /bin/sed -i 's/em1/eth0/g' /etc/sysconfig/network-scripts/ifcfg-eth0
  ignore_errors: True
  tags: base

- name: configure network devicename from em to eth
  command: /bin/rm -f /etc/udev/rules.d/70-persistent-net.rules
  ignore_errors: True
  tags: base

- name: configure local link disable
  lineinfile: dest=/etc/sysconfig/network line="NOZEROCONF=yes"
  ignore_errors: True
  tags: base

- name: configure ipv6 disable
  lineinfile: dest=/etc/sysconfig/network line="NETWORKING_IPV6=no"
  ignore_errors: True
  tags: base

- name: configure limits of noproc and nofile
  template: src=limits.conf dest=/etc/security/limits.conf
  ignore_errors: True
  tags: base

- name: configure dns server
  template: src=resolv.conf dest=/etc/resolv.conf
  ignore_errors: True
  tags: base

- name: configure hosts file
  template: src=hosts dest=/etc/hosts
  ignore_errors: True
  tags: base

- name: configure kernel file
  template: src=sysctl.conf dest=/etc/sysctl.conf
  ignore_errors: True
  tags: base

- name: configure sudoers file
  template: src=sudoers dest=/etc/sudoers
  ignore_errors: True
  tags: base

- name: configure ntp config file
  template: src=ntp.conf dest=/etc/ntp.conf
  ignore_errors: True
  tags: base

- name: configure ntpdate
  command: ntpdate 0.centos.pool.ntp.org
  tags: base
  ignore_errors: True

- name: configure hardclock
  command: /sbin/hwclock --systohc
  ignore_errors: True
  tags: base

- name: stop some service
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - abrt-ccpp
    - abrt-oops
    - abrtd
    - acpid  
    - atd
    - auditd
    - haldaemon 
    - iptables
    - ip6tables
    - lvm2-monitor
    - mdmonitor
    - messagebus 
    - psacct  
    - rdisc
    - saslauthd
    - restorecond
    - smartd  
  ignore_errors: True
  tags: base

- name: install epel packages
  command: rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  ignore_errors: True  
  tags: base

- name: yum install packages
  yum: name={{ item }} state=latest
  with_items:
    - monit
    - dstat
    - net-snmp
    - net-snmp-utils
    - OpenIPMI
    - OpenIPMI-tools
  ignore_errors: True 
  tags: base

- name: start some service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - ntpd
    - monit
    - snmpd
  ignore_errors: True
  tags: base

- name: yum update all
  shell: /usr/bin/yum -y update && /usr/bin/yum -y clean all
  tags: base
