---
# file: roles/pio/tasks/main.yml

- name: get predictionio 0.9.4
  copy: src=/usr/local/src/PredictionIO-0.9.4.tar.gz dest=/opt/PredictionIO-0.9.4.tar.gz
  tags: pio

- name: decompression tgz file
  command: tar -zxvf /opt/PredictionIO-0.9.4.tar.gz -C /opt/
  tags: pio

- name: pio-env.sh file
  template: src=pio-env.sh dest=/opt/PredictionIO-0.9.4/conf/pio-env.sh
  tags: pio

- name: chown pio
  command: chown -R pio:pio /opt/PredictionIO-0.9.4
  tags: pio

- name: symbolink
  command: ln -s /opt/PredictionIO-0.9.4 /opt/pio
  tags: pio

- name: chown pio
  command: chown -R pio:pio /opt/pio
  tags: pio

- name: delete tar gz
  command: rm -f /opt/PredictionIO-0.9.4.tar.gz
  tags: pio

- name: add customizable log4j.properties
  copy: src=files/custom-log4j.properties dest=/opt/pio/conf/custom-log4j.properties mode=0755
  tags:
    - pio
    - new-settings
